# Generated by Django 5.2.1 on 2025-05-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_updated_at_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Dispatched to officer', 'Dispatched to officer'), ('Draft', 'Draft'), ('Finalized draft', 'Finalized draft'), ('Signed and dispatched to CD/HM', 'Signed and dispatched to CD/HM')], default='Dispatched to officer', max_length=50),
        ),
    ]
