# Generated by Django 5.2.1 on 2025-05-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
