# Generated by Django 5.2.1 on 2025-05-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_reminder_is_dismissed_reminder_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('dispatched-officer', 'Dispatched to officer'), ('draft', 'Draft'), ('finalized-draft', 'Finalized draft'), ('signed-dispatched', 'Signed and dispatched to CD/HM')], default='dispatched-officer', max_length=50),
        ),
    ]
